services:
  cdmo:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: cdmo_app

    volumes:
      - .:/CDMO-PROJECT-

    # Load environment variables from .env file 
    env_file:
      - .env

    stdin_open: true    # Keep STDIN open
    tty: true           # Allocate a pseudo-TTY
    command: /bin/bash  # Start with bash
