@echo off
echo Creating virtual environment...
python -m venv venv

echo Activating the virtual environment...
call venv\Scripts\activate.bat

echo Installing pipreqs...
pip install pipreqs

echo Installing dependencies from import statements...
pipreqs . --force --encoding utf-8

echo Generating requirements.txt...
pip freeze > requirements.txt

echo Building Docker image...
docker-compose build

echo Starting container...
docker-compose up -d

echo Entering container...
docker exec -it cdmo_app bash